---
- hosts: buildkite-agents
  tags: [buildkite, ci, build_capability, "bc_k8s-test-infra"]
  gather_facts: true

  vars:
    vars_file: vars.yaml

  handlers:
    - name: Restart Buildkite
      systemd: name=buildkite-agent@{{ item }} state=restarted
      become: yes
      with_sequence: start=1 end={{ agent_count }} stride=1

  pre_tasks:
    - name: Include variables from file
      include_vars: "{{ vars_file }}"
      tags: [always]

  roles:
    - role: golang
      golang_version: "{{ go_version }}"
      become: yes
      tags: [golang]

    - role: geerlingguy.docker
      docker_package: "{{ docker_package_name }}"
      become: yes
      tags: [docker]

    - role: andrewrothstein.ansible-bazel
      become: yes
      tags: [bazel]

    - role: dockerprune
      become: yes
      tags: [baseline, docker, dockerprune]

  tasks:
    - name: "{{ agent_username }} docker config dir exists"
      file:
        path: "{{ agent_homedir }}/.docker"
        state: "directory"
        owner: "{{ agent_username }}"
        group: "{{ agent_username }}"
        mode: 0700
      become: yes
      tags: [docker]

    - name: "allow {{ agent_username }} to docker"
      user:
        name: "{{ agent_username }}"
        append: yes
        groups: docker
      become: yes
      tags: [docker]

    - name: add capability tags to agent
      lineinfile:
        path: "{{ agent_configdir }}/buildkite-agent.cfg"
        regexp: "^tags=(?!.*capable_of_building.*)(.*)$" # ?! is negative lookahead, to prevent multiple runs re-appending
        backrefs: yes
        line: "tags=\\1,capable_of_building=k8s-test-infra,docker={{ docker_version }},golang={{ go_version }}"
      notify:
        - "Restart Buildkite"
      become: yes
      tags: [agent, docker, golang]

    - name: run goss tests
      goss:
        path: "tests/goss.yaml"
        format: tap
        vars_path: "tests/{{ environment_name }}.vars.goss.yaml"
      become: yes
      tags: [tests, goss]
